# a mybinder.org-ready environment for demoing bifrost widget
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate code_snippet-demo
#
name: bifrost-widget-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=3,<4.0.0a0
  # labextension build dependencies
  - nodejs >=14,<15
  - pip
  - wheel
  # additional packages for demos
  - pandas
  - setuptools
  - codecov
  - pandas
  - scikit-learn
  - jupyter-packaging
  - yarn
