name: Publish Package

on:
  push:
    branches: test

jobs:
  Publish-To-Pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install jupyterlab
          python -m pip install -U pip setuptools jupyter_packaging
          sudo apt-get install jq

      - name: Upload Package with `twine` 👏
        #         uses: yaananth/twine-upload@v2
        env:
          RUNNER: ${{ toJson(runner) }}
          SECRETS: ${{ toJson(secrets) }}
        run: |
          temp=$(echo $RUNNER | jq '.temp')
          token=$(echo $SECRETS | jq '.TOKEN')
          workspace=$(echo $RUNNER | jq '.workspace')
          
          python -m pip install pip twine
          python -m pip install -r requirements.txt
          python setup.py sdist --dist-dir $temp
          
          echo "[distutils]\nindex-servers=pypi\n[pypi]\nusername=__token__\npassword=$token\n" >> $workspace/twine.pypirc
          cat twine.pypirc
          echo "$workspace/twin.pypirc"
          
          # twine upload --config-file $workspace/twine.pypirc $temp/*.tar.gz --skip-existing


