name: Publish Package

on:
  push:
    branches: test

jobs:
  Publish-To-Pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools

        - name: Install Publishing Dependencies
          run: |
            python setup.py sdist bdist_wheel
            pip install twine
        - name: twine-upload
          uses: yaananth/twine-upload@v2
            env:
            RUNNER: ${{ toJson(runner) }}
            SECRETS: ${{ toJson(secrets) }}

